export const ErrorCodes = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  USERNAME_TAKEN: "USERNAME_TAKEN",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  TOPIC_NOT_FOUND: "TOPIC_NOT_FOUND",
  LOG_NOT_FOUND: "LOG_NOT_FOUND",
  AUTH_ERROR: "AUTH_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  PROFILE_NOT_FOUND: "PROFILE_NOT_FOUND",
} as const;

export type ErrorCodes = keyof typeof ErrorCodes;
